### PR TITLE
fix #27 (rmq certification is changed)

### LINKED ISSUE #27: rmq certification is changed
**Issue branch: develop** 

Local host VOLTTRON_HOME is mounted.

The cert file is changed for every execution.

I think it makes sense that the cert file created in the host mount folder is not changed.

It is expected to be a problem especially when using external interfaces such as federation and shovel.

### PR DESCRIPTION
**Pull request by GHYOON**
Issue: #27 

To avoid CA conflict, a conditional statement was added.
This conditional statement checks the system environment variable(**SKIP_CA_CREATE_CERTIFICATION**) and skips the RMQ CA certification generation code.

This avoids regenerating rmq ca certification when using a local vhome.

To do this, set the environment variable as follows in the docker-compose file.

```yaml
    environment:
      - SKIP_CA_CREATE_CERTIFICATION=true
```

### CODE REVIEW

**Comment by bonicim** [comment]
@GHYOON Did you run docker-compose with an updated docker-compose file and did the change work as expected when you mounted your volttron home? Are there any other changes required in the docker-compose file that need to be added in order for this use case to work?

**Comment by GHYOON** [comment]
@bonicim 
When I mounted vhome and ran the test, it worked as expected.
The test sequence is as follows:

1. docker-compose -f docker-compose-rmq.yml up
```yaml
     volumes:
       -./platform_config_rmq.yml:/platform_config.yml
       -./configs:/home/volttron/configs
       -./vhome:/home/volttron/.volttron
     environment:
       -CONFIG=/home/volttron/configs
       -LOCAL_USER_ID=1000
      #-SKIP_CA_CREATE_CERTIFICATION=true
```

2. docker-compose -f docker-compose-rmq.yml up

```yaml
     volumes:
       -./platform_config_rmq.yml:/platform_config.yml
       -./configs:/home/volttron/configs
       -./vhome:/home/volttron/.volttron
     environment:
       -CONFIG=/home/volttron/configs
       -LOCAL_USER_ID=1000
       -SKIP_CA_CREATE_CERTIFICATION=true

```

**Comment by bonicim** [comment]
@GHYOON Thanks for the quick response. One more request. Can you please merge the latest from `develop` into your branch? I just made one little change to our CI/CD pipeline so that it runs whenever someone makes a PR to 'develop'.

**Comment by GHYOON** [comment]
@bonicim I have updated my `develop` branch to the latest.
But I don't know about CI/CD. Is there anything I have to do when requesting a PR?

**Comment by bonicim** [comment]
> @bonicim I have updated my `develop` branch to the latest.
> But I don't know about CI/CD. Is there anything I have to do when requesting a PR?

I wanted you to merge the latest from develop into this PR. But I figured out how to do it for you and just added a new commit on your PR. You don't have to do anything when requesting a new PR; I just updated the repo's workflow to automatically test any PR's. So you're good.

**Pull request merged**
